version: '3.3'
services:
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file: secret.env
    volumes:
      - './rabbitmq:/var/lib/rabbitmq'
    
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    env_file: secret.env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/data/postgres'
    restart: unless-stopped
  
  tt-sender:
    restart: unless-stopped
    links:
      - rabbitmq
    env_file:
      - secret.env
    image: atopiraka/tt-sender:latest
    
  tt-api:
    restart: unless-stopped
    links:
      - rabbitmq
      - postgres
    env_file:
      - secret.env
    image: atopiraka/tt-api:latest
    ports:
      - '8080:8080'
      
  tt-scheduler:
    restart: unless-stopped
    links:
      - rabbitmq
      - postgres
    env_file:
      - secret.env
    image: atopiraka/tt-scheduler:latest
    
volumes:
  postgres:

